image: python:3.7

pipelines:
  custom:
    Manual pipeline:
    #- step:
    #    name: Lint Python files
    #    caches:
    #        - pip
    #    script:
    #        - pip install requests
    #        - pip install pylint
    #        - pylint $BITBUCKET_CLONE_DIR/bin/input_module_*.py --disable=broad-except,logging-fstring-interpolation,missing-module-docstring,line-too-long,too-many-locals,too-many-nested-blocks
    #- step:
    #    name: Security test using Bandit
    #    caches:
    #        - pip
    #    script:
    #        - pip install bandit
    #        - bandit -r $BITBUCKET_CLONE_DIR/bin/*.py
    - step:
        name: Build TA-strava-for-splunk.tgz
        script:
          - ./build.sh
          #- ls -lah /tmp
          - mv /tmp/*.tgz $BITBUCKET_CLONE_DIR
          #- ls -lah $BITBUCKET_CLONE_DIR
        artifacts:
          - TA-strava-for-splunk.tgz
    - step:
        name: Splunk AppInspect Test
        caches:
            - pip
        script:
            #- ls -lah $BITBUCKET_CLONE_DIR
            - wget --output-document splunk-appinspect.tar.gz https://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz
            - pip install splunk-appinspect.tar.gz 
            - splunk-appinspect inspect $BITBUCKET_CLONE_DIR/$APP_NAME.tgz --mode precert --included-tags cloud
            #- splunk-appinspect inspect /tmp/$APP_NAME*.tgz --mode precert --included-tags cloud | grep "\[  F  ]\|\[  E  ]\|\[  M  ]\[  W  ]"
  branches:
    master:
      - step:
          name: Deploy to Splunkbase
          script:
            - wget --output-document splunk-appinspect.tar.gz https://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz
            - pip install splunk-appinspect.tar.gz 
            - mkdir /tmp/$APP_NAME
            - git archive --format tar HEAD | tar --exclude-vcs --exclude=bitbucket-pipelines.yml -xC /tmp/$APP_NAME
            - splunk-appinspect inspect /tmp/$APP_NAME --mode precert --included-tags cloud
            - cd /tmp
            - tar czvf /tmp/$APP_NAME.tgz $APP_NAME
            - ls -ltr /tmp
            - curl -u $SPLUNK_USR:$SPLUNK_PWD --request POST "https://splunkbase.splunk.com/api/v1/app/$SPLUNK_APP_ID/new_release/" -F "filename=$APP_NAME.tgz" -F "files[]=@/tmp/$APP_NAME.tgz" -F "splunk_versions=$SPLUNK_VER" -F "visibility=$SPLUNK_VISIBILITY"
            # - pip install jq
            # - response=$(curl -X GET -u $SPLUNK_USR:$SPLUNK_PWD --url "https://api.splunk.com/2.0/rest/login/splunk" | jq -r '.data.token')
            # - curl -X POST -H "Authorization: bearer ${response}" -H "Cache-Control: no-cache" -F "app_package=@/tmp/$APP_NAME.tgz" -F "included_tags=cloud" --url "https://appinspect.splunk.com/v1/app/validate"