name: Run tests and store artifact
on: 
  push:
    branches:
      - develop
    # Avoid running the CI/CD pipeline when updating the GitHub Actions workflow
    paths-ignore:
      - '**/develop-build-ta.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.7
      uses: actions/setup-python@main
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@main
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # See if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('.ci/requirements-${GITHUB_REF##*/}.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Set variables
      run: |
        VER=$(cat VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV
    - name: Install dependencies
      run: | 
        pip install --upgrade pip
        pip install -r .ci/requirements-${GITHUB_REF##*/}.txt
    - name: Lint with pylint
      run: pylint ./package/bin/strava_*.py --disable=broad-exception-raised,broad-exception-caught,logging-fstring-interpolation,missing-module-docstring,line-too-long,too-many-locals,too-many-nested-blocks,import-error
    - name: Bandit Security Test
      run: bandit -r ./package/bin/*.py
    - name: Run ucc-gen build
      run: ucc-gen build --ta-version ${{ env.VERSION }}
    - name: Set right file permissions
      run: chmod -R u+rw,g-rwx,o-rwx ./output
    - name: Create Splunk app package
      run: slim package output/TA-strava-for-splunk
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        path: ./TA-strava-for-splunk-${{ env.VERSION }}.tar.gz
        retention-days: 5
    - name: Splunk AppInspect Test
      run: splunk-appinspect inspect ./TA-strava-for-splunk-${{ env.VERSION }}.tar.gz --mode test --included-tags cloud
