name: Run tests and store artifact
on: 
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # See if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('.ci/requirements-${GITHUB_REF##*/}.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Set variables
      run: |
        VER=$(cat VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV
    - name: Install dependencies
      run: | 
        pip install --upgrade pip
        pip install -r .ci/requirements-${GITHUB_REF##*/}.txt
    - name: Lint with pylint
      run: pylint ./package/bin/strava_*.py --disable=broad-except,logging-fstring-interpolation,missing-module-docstring,line-too-long,too-many-locals,too-many-nested-blocks
    - name: Bandit Security Test
      run: bandit -r ./package/bin/*.py
    - name: Run ucc-gen
      run: ucc-gen --ta-version ${{ env.VERSION }}
    - name: Remove troublesome METADATA file to bypass AppInspect error
      run: rm ./output/TA-strava-for-splunk/lib/charset_normalizer-2.0.5.dist-info/METADATA
    - name: Set right file permissions
      run: chmod -R u+rw,g-rwx,o-rwx ./output
    - name: Create Splunk app package
      run: slim package output/TA-strava-for-splunk
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: path: ./TA-strava-for-splunk-${{ env.VERSION }}.tar.gz
        path: ./TA-strava-for-splunk-${{ env.VERSION }}.tar.gz
        retention-days: 5
    - name: Splunk AppInspect Test
      run: splunk-appinspect inspect ./TA-strava-for-splunk-${{ env.VERSION }}.tar.gz --mode test --included-tags cloud